### PR TITLE
Update handling of date fields in line with changes made in for for d…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ev/core#561 and bump version and min civicrm version

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@seamuslee001 thanks for this - I'm happy with it if the tests pass - which they should from this patch - just not sure if there is an infra issue

**Comment by seamuslee001** [comment]
@eileenmcnaughton i think its because i'm not whitelisted you have to do it I think

**Comment by eileenmcnaughton** [comment]
I did - but I just did again - it errors straight away

**Comment by eileenmcnaughton** [comment]
Yay

**Pull request merged**
