### PR TITLE
Extended Activity Report: custom data on Assigned / Target contact displays Incorrectly

### PR DESCRIPTION
**Pull request by davidjosephhayes**
List custom data with a prefix on the Extended Activity report displays the option value value not the label. I believe this is due to these field having a prefix. The underlying base class does not catch that these need translated.

This pull request modifies to base class to run a rudimentary pattern match for these cases and translate the field values as necessary.

## Before
before

## After
after

Let me know if there is a better way to approach this.

### CODE REVIEW

**Comment by davidjosephhayes** [comment]
bump

**Comment by eileenmcnaughton** [comment]
I just tested this & I couldn't replicate it  - I note the PR is stale so the code has changed in the meantime

image

**Comment by davidjosephhayes** [comment]
Dope! It is fixed in 5.9.

**Pull request closed without merging**
