### PR TITLE
expose billing name for contribution in extended report

### PR DESCRIPTION
**Pull request by yashodha**
expose billing name for contribution in extended report

Contribution View
contri

Report results
report

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha this makes sense - can you add comment blocks & then I'll merge

**Comment by yashodha** [comment]
@eileenmcnaughton 
have added comments for the report

**Comment by eileenmcnaughton** [comment]
thanks @yashodha

**Comment by eileenmcnaughton** [comment]
@yashodha this caused test fails - just an enotice I think but it relates

**Pull request merged**
