### PR TITLE
Custom field label is not displayed in some the reports

### PR DESCRIPTION
**Pull request by ahed-compucorp**
## Overview
When we run a report for contacts with custom fields of type select, we see the custom field value instead of the custom field label.

I created a custom fieldset called `select` and has two fields `field 1`, `field 2`. When running the "Extended Report - Relationships" report, we will see the following result.

Screenshot from 2021-02-04 12-12-57

It happens for any report that has two columns for the same custom field.

## Technical details
Behind the scenes, the technical problem is CiviCRM and nz.co.fuzion.extendedreport depend on the name convention for the custom field to be like fields_custom_55 . However, when we have multiple columns for the same field as in ”Extended Report - Relationships” report, we have to break from the convention and called them uniquely `fields_custom_contact_a__55` and `fields_custom_contact_b__55` but also we have to handle custom field labels accordingly and this PR will do that.

Screenshot from 2021-02-04 19-39-06

Because the problem affects multiple reports, I decided to fix it in the base class `ExtendedReport.php`. 

The changes are the following :
 - 1st block : will remove the prefix from fieldAlias so `CRM_Core_BAO_CustomField::getKeyID` can get the ID properly. (e.g. if the column has `target_` as a prefix `custom_target__50` will become `custom_50`)
 - 2st block: will guess the column and remove the prefix.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
(I'm not sure if that works - I normally have to remember /test)

**Comment by eileenmcnaughton** [comment]
@ahed-compucorp thanks for this - what you are saying & your approach makes sense - it's failing on enotices so probably needs a minor fix rather than a fundamental change

**Comment by ahed-compucorp** [comment]
I will run the tests locally and check it again.
Thank you for your time.

**Comment by eileenmcnaughton** [comment]
Thanks - I'm gonna rely on your testing & the tests here. Code seems sane & the luxury of an extension vs core is not having to have as high review standards :-)

**Comment by ahed-compucorp** [comment]
@eileenmcnaughton 
Can I ask when will be the next release?

**Comment by eileenmcnaughton** [comment]
@ahed-compucorp I just tagged one for you - note I always tag new releases against the latest stable civi-version to simplify testing & support but there are no known issues against other recent-ish releases

**Pull request merged**
