### PR TITLE
expose membership fields for report

### PR DESCRIPTION
**Pull request by yashodha**
expose membership fields for report

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@yashodha does this lead to a misleading result if there are multiple memberships associated with the contact?

**Comment by eileenmcnaughton** [comment]
add to whitelist

**Comment by eileenmcnaughton** [comment]
test this please

**Comment by seamuslee001** [comment]
civici

**Comment by eileenmcnaughton** [comment]
Just noting that the unit test for this will need to demonstrate that it does not lead to the wrong number of rows or incorrect calculations in 'SUM' via the left join when a contact has multiple memberships

**Comment by eileenmcnaughton** [comment]
This is stale - closing

**Pull request closed without merging**
