### PR TITLE
add contact custom data for case pivot report

### PR DESCRIPTION
**Pull request by yashodha**
add contact custom data for case pivot report

### CODE REVIEW

**Comment by yashodha** [comment]
@eileenmcnaughton 
it is strange that not the same custom data appear in row and column for case pivot report

e,g 
Ask amount is Case custom data  that appears in row and not column. Can you please help me rectify this so the custom data is exposed in both row and column? Thanks!

row

column

**Comment by eileenmcnaughton** [comment]
@yashodha  - what field type is `ask` - it deliberately excludes open ended field types (e.g text, with no option group) to avoid endless columns

**Comment by yashodha** [comment]
@eileenmcnaughton Ask amount is Money/Text

ask_amount

Can you please point me so that I can have this column as well? Thanks!

**Comment by eileenmcnaughton** [comment]
@yashodha  I don't think it's a change - it's [these lines ](https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/b24258b837da43e5bf8d8712ec21d5149d4fa5ff/CRM/Extendedreport/Form/Report/ExtendedReport.php#L3055-L3059 )- but if you remove that check there needs to be some sort of check to ensure there are not hundreds of distinct strings to be make an insane number of column headers

**Comment by yashodha** [comment]
@eileenmcnaughton this PR can be merged. Can you please do the needful?

**Comment by yashodha** [comment]
@eileenmcnaughton thanks!

**Pull request merged**
