### PR TITLE
 Basic addition of contribution recur report, translation fn

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@petednz I feel you had an interest in this at one point

**Comment by petednz** [comment]
sorry not that i recall. translation of the report to other languages?

**Comment by eileenmcnaughton** [comment]
@petednz - no recurring contribution report in extended reports - I can't recall why we discussed it though

**Comment by petednz** [comment]
@jitendrapurohit can you review?

**Comment by eileenmcnaughton** [comment]
@petednz this doesn't need review - it's an extension - but maybe you meant to tag the civixero one?

**Pull request merged**
